### ISSUE TITLE
Add macro for cleanup attribute

### ISSUE THREAD

**Issue by llllllllll** [tmathmeyer/C-reference-count#1]
gcc support the `cleanup` variable attribute which allows you to attach a callback to a variable to be executed when it goes out of scope. You just need to wrap `lose_scope` in a function that has one more level of indirection like:

``` c
void _lose_scope_ref(char **refref) {
    lose_scope(*refref);
}
```

Then you can wrap this up in a macro like:

``` c
#define autocleanup __attribute__((cleanup(_lose_scope_ref)))
```

Now we can just do:

``` c
int f() {
    autocleanup string *cs = _string("test", True);
    /* do some stuff */
    return 0;  /* no need to call L */
}
```

p.s.: make `get_refcount` return an `ssize_t`

**Comment by tmathmeyer** [comment]
TopGNU?

**Comment by tmathmeyer** [comment]
it doesnt look like there is a way to have it call S automatically for a "scoped" type :(

**Comment by llllllllll** [comment]
hype
